
spring:
  datasource:
    baseline-on-migrate: true
    username: sa
    password: yourStrong(!)Password
    url: jdbc:sqlserver://localhost:1433;databaseName=nordestebank;encrypt=false;integratedSecurity=false;trustServerCertificate=true;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
