-- Inserts para as contas de ID 1 a 10

-- Inserts de Contas
INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('FISICA', 'João Silva', '12345678901', '11 987654321', 'joao.silva@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('JURIDICA', 'Maria Souza', '98765432109', '21 987654321', 'maria.souza@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('FISICA', 'Pedro Santos', '45678912304', '31 987654321', 'pedro.santos@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('JURIDICA', 'Ana Oliveira', '32165498708', '41 987654321', 'ana.oliveira@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('FISICA', 'Carlos Rodrigues', '65498732105', '51 987654321', 'carlos.rodrigues@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('JURIDICA', 'Laura Mendes', '98732165403', '61 987654321', 'laura.mendes@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('FISICA', 'Lucas Fernandes', '78932165402', '71 987654321', 'lucas.fernandes@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('JURIDICA', 'Julia Costa', '12398745606', '81 987654321', 'julia.costa@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('FISICA', 'Mateus Almeida', '98745632100', '91 987654321', 'mateus.almeida@example.com');

INSERT INTO TB_CONTA (TIPO_CONTA, TITULAR, CPF_CNPJ, DDD_TELEFONE, EMAIL) 
VALUES ('JURIDICA', 'Lara Ribeiro', '65432178905', '10 987654321', 'lara.ribeiro@example.com');

-- Insertes de Endereços para contas

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '12345-678', 'Centro', 'Rua A', '100', 'Apartamento 101', 'Cidade A', 'UF A', 1);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '98765-432', 'Centro', 'Rua B', '200', 'Sala 201', 'Cidade B', 'UF B', 2);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '54321-876', 'Centro', 'Rua C', '300', 'Casa 301', 'Cidade C', 'UF C', 3);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '87654-321', 'Centro', 'Rua D', '400', 'Sala 401', 'Cidade D', 'UF D', 4);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '13579-246', 'Centro', 'Rua E', '500', 'Apartamento 501', 'Cidade E', 'UF E', 5);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '86420-975', 'Centro', 'Rua F', '600', 'Sala 601', 'Cidade F', 'UF F', 6);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '98765-432', 'Centro', 'Rua G', '700', 'Casa 701', 'Cidade G', 'UF G', 7);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '54321-876', 'Centro', 'Rua H', '800', 'Sala 801', 'Cidade H', 'UF H', 8);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '87654-321', 'Centro', 'Rua I', '900', 'Apartamento 901', 'Cidade I', 'UF I', 9);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '13579-246', 'Centro', 'Rua J', '1000', 'Sala 1001', 'Cidade J', 'UF J', 10);

-- Inserts adicionais para contas específicas (ID 1, 2, 3, 4)
INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '12345-678', 'Centro', 'Rua K', '1100', 'Apartamento 1101', 'Cidade K', 'UF K', 1);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '12345-678', 'Centro', 'Rua L', '1200', 'Casa 1201', 'Cidade L', 'UF L', 1);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '98765-432', 'Centro', 'Rua M', '1300', 'Sala 1301', 'Cidade M', 'UF M', 2);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '98765-432', 'Centro', 'Rua N', '1400', 'Sala 1401', 'Cidade N', 'UF N', 2);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('RESIDENCIAL', '54321-876', 'Centro', 'Rua O', '1500', 'Apartamento 1501', 'Cidade O', 'UF O', 3);

INSERT INTO TB_ENDERECO (TIPO_ENDERECO, CEP, BAIRRO, LOGRADOURO, NUMERO, COMPLEMENTO, CIDADE, UF, CONTA_ID)
VALUES ('COMERCIAL', '54321-876', 'Centro', 'Rua P', '1600', 'Sala 1601', 'Cidade P', 'UF P', 4);
